### ISSUE TITLE
T2 development in a virtual environment

### ISSUE THREAD

**Issue by Frijol** [tessel/docs#67]
We have a virtualbox for development, discussed a bit [here](https://forums.tessel.io/t/contributing-to-t2-without-the-hardware/1686/10) but it would be better to have a readme walking people through setting up  virtual development & explaining what is & isn't possible

**Comment by sidwarkd** [comment]
@Frijol @tcr Bump. I tried doing this from the docs and gave up. There were some holes that I'm sure I could have worked through but I think you'd get more engagement if it was well documented and easy to set up.

**Comment by tcr** [comment]
Hey @sidwarkd, should have something out in the next few days—right now the issue is that updating the openwrt stream is actually leaving the x86 Virtualbox images corrupted, so we don't have an up-to-date image to work with.

**Comment by Frijol** [comment]
This lives on the [T2-VM repo](https://github.com/tessel/t2-vm). Do we want to also add its readme to /docs?
